{"name": "test_add2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 300 == 290\n  +300\n  -290", "trace": "def test_add2():\n>       assert 300 == add(10,50,230)\nE       assert 300 == 290\nE         +300\nE         -290\n\ntest_1_py30.py:24: AssertionError"}, "start": 1596630454463, "stop": 1596630454463, "uuid": "4bbb31ab-d343-4c08-b9ab-b9727f1692ce", "historyId": "8bbff1e18bc2750ab721f2e709ed8b2d", "testCaseId": "8097b1df958728804ceae5b51235a85d", "fullName": "test_1_py30#test_add2", "labels": [{"name": "suite", "value": "test_1_py30"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "14232-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1_py30"}]}