{"name": "test_login_failed_invalid_data[case1]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '18684720553', 'passwd': '', 'check': '请输入密码'}"}], "start": 1599055535563, "stop": 1599055537132, "uuid": "c65a6997-307b-4050-ac17-19861b9b9069", "historyId": "1352fcf7b98c3a086b04449cfbf3bcb3", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "CY-20190809JTFQ"}, {"name": "thread", "value": "5776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}